name: Build and Push qBittorrent
on:
  schedule:
    - cron: '0 0 * * 6'  # Run every Saturday at 00:00 (midnight)
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: TestEnv
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run build script
      run: |
        chmod +x build.sh
        ./build.sh . ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_ACCESS_TOKEN }}